# Generated by Django 2.1.1 on 2018-10-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='campoprueba',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
