# Generated by Django 2.1.2 on 2018-10-08 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20181006_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('idSuscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_peticion', models.DateField(auto_now=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emisor', to=settings.AUTH_USER_MODEL)),
                ('idGrupoSuscribio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.Grupo')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
