# Generated by Django 2.1.1 on 2018-10-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_skin_campoprueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skin',
            name='campoprueba',
        ),
        migrations.AddField(
            model_name='user',
            name='campoprueba',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
