# Generated by Django 2.1.2 on 2018-10-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanager',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/deafult-profile-image.png', upload_to='avatars/'),
        ),
    ]
