# Generated by Django 2.1.1 on 2018-09-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20180920_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='FechaBajaPublicacion',
            field=models.DateField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='FechaModiPublicacion',
            field=models.DateField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='FechaPublicacion',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
    ]
