# Generated by Django 2.1.2 on 2018-10-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_usermanager_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='avatar',
            field=models.ImageField(blank=True, default='../static/avatars/s.png', upload_to='avatars/'),
        ),
    ]
