# Generated by Django 2.1.1 on 2018-09-20 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20180920_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='FechaBajaG',
            field=models.DateField(blank=True, default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='FechaCreacionG',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Creacion'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='FechaModiG',
            field=models.DateField(blank=True, default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='FechaBajaPublicacion',
            field=models.DateField(blank=True, default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='FechaModiPublicacion',
            field=models.DateField(blank=True, default=None, editable=False),
        ),
    ]
