# Generated by Django 2.1.1 on 2018-09-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20180920_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='FechaBajaG',
            field=models.DateField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='FechaModiG',
            field=models.DateField(default=None, editable=False),
        ),
    ]
