# Generated by Django 2.1.2 on 2018-10-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20181011_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/s.png', upload_to='avatars/'),
        ),
    ]
