# Generated by Django 2.1.1 on 2018-09-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20180920_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='FechaBajaG',
            field=models.DateField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='FechaModiG',
            field=models.DateField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='FechaBajaPublicacion',
            field=models.DateField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='FechaModiPublicacion',
            field=models.DateField(default=None, editable=False, null=True),
        ),
    ]
