# Generated by Django 2.1.2 on 2018-10-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20181011_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='avatar',
            field=models.ImageField(blank=True, default='images/s.png', upload_to='avatars/'),
        ),
    ]
