# Generated by Django 2.1.1 on 2018-09-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20180920_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='Titulo',
            field=models.CharField(max_length=30),
        ),
    ]
