# Generated by Django 2.1.1 on 2018-09-20 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0009_auto_20180920_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('ContenidoComent', models.TextField(null=True)),
                ('FechaComentario', models.DateField(auto_now=True, verbose_name='Date')),
                ('FechaModiComentario', models.DateField(default=None, editable=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='Destacar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentario',
            name='idPublicacionC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Publicacion'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='idUserComento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
