# Generated by Django 2.1.1 on 2018-09-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('social', '0010_auto_20180920_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaUsuario',
            fields=[
                ('idCategoriaU', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCategoriaU', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('idPermisos', models.AutoField(primary_key=True, serialize=False)),
                ('NombrePerm', models.CharField(max_length=30)),
                ('EditarComentarios', models.BooleanField(default=False)),
                ('EliminarComentarios', models.BooleanField(default=False)),
                ('EditarPublicacion', models.BooleanField(default=False)),
                ('EliminarPublicacion', models.BooleanField(default=False)),
                ('EditarGrupo', models.BooleanField(default=False)),
                ('EliminarGrupo', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='CategoriaGrupo',
        ),
        migrations.RenameField(
            model_name='categoriagrupo',
            old_name='NombreCategoria',
            new_name='NombreCategoriaG',
        ),
        migrations.RenameField(
            model_name='categoriagrupo',
            old_name='idCategoria',
            new_name='idCategoriaG',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='ContenidoComent',
            new_name='ContenidoComentario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='FechaBajaComentario',
            field=models.DateField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usergrupos',
            name='Permisos',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='social.Permisos'),
            preserve_default=False,
        ),
    ]
