# Generated by Django 2.1.2 on 2018-10-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20181014_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='avatar',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
