# Generated by Django 2.1.1 on 2018-09-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_auto_20180920_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='idGrupoPu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.Grupo'),
        ),
    ]
