# Generated by Django 2.1.1 on 2018-09-25 23:41

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('social', '0012_auto_20180920_1855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaGrupo',
            new_name='PrivacidadGrupo',
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='CategoriaGrupo',
            new_name='NivelAcceso',
        ),
        migrations.RenameField(
            model_name='privacidadgrupo',
            old_name='NombreCategoriaG',
            new_name='Privacidad',
        ),
        migrations.RenameField(
            model_name='privacidadgrupo',
            old_name='idCategoriaG',
            new_name='idPrivacidadG',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='NecesitaInvitacion',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='Visibilidad',
        ),
    ]
