# Generated by Django 2.1.2 on 2018-10-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_denunciausuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='denunciausuarios',
            name='Contenido',
            field=models.TextField(default='algo', max_length=150),
            preserve_default=False,
        ),
    ]
