# Generated by Django 2.1.2 on 2018-10-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_denunciausuarios_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='Borrador',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='Eliminado',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='Publicado',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='Estado',
            field=models.IntegerField(choices=[(1, 'Publicado'), (2, 'Eliminado'), (3, 'Borrador')], default=1),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='Destacar',
            field=models.IntegerField(choices=[(1, 'Destacado'), (2, 'No destacado')], default=1),
        ),
    ]
