# Generated by Django 2.1.1 on 2018-09-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_auto_20180925_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('idCarrera', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCarrera', models.CharField(max_length=50)),
            ],
        ),
    ]
