# Generated by Django 2.1.2 on 2018-10-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_auto_20181026_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='Destacar',
            field=models.IntegerField(choices=[(1, 'Destacado'), (2, 'No destacado')], default=1),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='Estado',
            field=models.IntegerField(choices=[(1, 'Publicado'), (2, 'Eliminado'), (3, 'Borrador')], default=1),
        ),
    ]
