# Generated by Django 2.1.1 on 2018-09-29 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_auto_20180928_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadopublicacion',
            old_name='Estado',
            new_name='NombreEstado',
        ),
    ]
