# Generated by Django 2.1.2 on 2018-10-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_auto_20181026_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='Estado',
            field=models.IntegerField(choices=[(1, 'Publicado'), (2, 'Eliminado'), (3, 'Borrador')], default=1),
        ),
    ]
