# Generated by Django 2.1.1 on 2018-10-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_auto_20180929_0022'),
        ('social', '0016_auto_20180929_0002'),
    ]

    operations = [
    ]
