# Generated by Django 2.1.1 on 2018-10-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_merge_20181002_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopublicacion',
            name='NombreEstado',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
