# Generated by Django 2.1.3 on 2018-11-09 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_suscripcion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEvento', models.CharField(max_length=30)),
                ('FechaEvento', models.DateField()),
                ('CreadorEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreadorEvento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='Destacar',
            field=models.IntegerField(choices=[(1, 'No destacado'), (2, 'Destacado')], default=1),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='Estado',
            field=models.IntegerField(choices=[(1, 'Publicado'), (2, 'Eliminado'), (3, 'Borrador'), (4, 'MURO')], default=1),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='Estado',
            field=models.IntegerField(choices=[(1, 'Publicado'), (2, 'Eliminado'), (3, 'Borrador'), (4, 'MURO')], default=1),
        ),
    ]
