# Generated by Django 2.1.3 on 2018-11-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_suscripcion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='Estado',
            field=models.IntegerField(choices=[(1, 'Publicado'), (2, 'Eliminado'), (3, 'Borrador'), (4, 'MURO')], default=1),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='Estado',
            field=models.IntegerField(choices=[(1, 'Publicado'), (2, 'Eliminado'), (3, 'Borrador'), (4, 'MURO')], default=1),
        ),
    ]
