# Generated by Django 2.1.1 on 2018-10-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_auto_20181002_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='Estado',
            new_name='Estado_id',
        ),
    ]
