# Generated by Django 2.1.3 on 2018-11-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_evento_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='Hora',
            field=models.TimeField(default=None),
        ),
    ]
