# Generated by Django 2.1.3 on 2018-11-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_auto_20181109_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='Hora',
            field=models.TimeField(),
        ),
    ]
