# Generated by Django 2.1.3 on 2018-11-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_auto_20181109_1327'),
        ('social', '0018_auto_20181102_1637'),
    ]

    operations = [
    ]
