# Generated by Django 2.1.3 on 2018-11-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_merge_20181109_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='NivelAcceso',
            field=models.IntegerField(choices=[(1, 'Publico'), (2, 'Privado')], default=1),
        ),
        migrations.DeleteModel(
            name='PrivacidadGrupo',
        ),
    ]
