# Generated by Django 2.1.3 on 2018-11-13 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0026_denunciagrupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idPerfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(blank=True, max_length=50, null=True)),
                ('localizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('carrera', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
