# Generated by Django 2.1.3 on 2018-11-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0027_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='universidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
