# Generated by Django 2.1.3 on 2018-11-14 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0028_perfil_universidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenunciaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenido', models.TextField(max_length=150)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userDenuncia', to=settings.AUTH_USER_MODEL)),
                ('idUsuarioDenunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userDenunciado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
