# Generated by Django 2.1.3 on 2018-11-14 02:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0029_auto_20181113_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspensionUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaSuspension', models.DateField(default=datetime.date.today, editable=False)),
                ('duracion', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
