# Generated by Django 2.1.3 on 2018-11-14 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0029_auto_20181113_2222'),
        ('social', '0029_auto_20181113_2300'),
    ]

    operations = [
    ]
