# Generated by Django 2.1.3 on 2018-11-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0029_auto_20181113_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuspensionUsuarios',
            new_name='SuspensionUsuario',
        ),
    ]
